steps:
  - name: gcr.io/cloud-builders/mvn
    entrypoint: mvn
    args: ["test"]
  - name: gcr.io/cloud-builders/mvn
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ["gcloud", "app", "deploy"]
  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', '$PROJECT_ID/$REPO_NAME','.' ]
images: ['$PROJECT_ID/$REPO_NAME']